name: publish-snapshot
on:
  push:
    branches:
      - '**'

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        loader: [common, fabric, forge, neoforge]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      - name: Setup JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: 21
          distribution: temurin
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Extracting version from properties
        shell: bash
        run: echo "version=$(cat gradle.properties | grep -w "\bversion" | cut -d= -f2)" >> $GITHUB_OUTPUT
        id: extract-version
      - name: Bumping version
        uses: TwelveIterations/bump-version@86901cde5897b550e2e98fbe8962afc401c23c8f
        with:
          version: ${{ steps.extract-version.outputs.version }}
          bump: patch
        id: bump-version
      - name: Publish
        run: ./gradlew :${{ matrix.loader }}:publish '-Pversion=${{ steps.bump-version.outputs.version }}-SNAPSHOT' '-PtwelveIterationsNexusUsername=${{ secrets.NEXUS_USER }}' '-PtwelveIterationsNexusPassword=${{ secrets.NEXUS_PASSWORD }}'
